DiasPHPora/wp-to-diaspora

class-diaspora.php
Load a smaller page when fetching the csrf-token.
=> Small optimisation for Diasphp

wp-to-diaspora.php
Optimise the procedure when first adding the settings to the database and when updating the settings due to an update to a new version of the plugin.
=> Optimise the options fresh install / updating procedure.

css/wp-to-diaspora.css, js/wp-to-diaspora.js, wp-to-diaspora.php
Many smaller code changes and optimisations.
Corrected typos and added more comments to facilitate understanding the code better.
=> Code cleanup

lib/class-api.php, lib/class-options.php, wp-to-diaspora.php
=> Remove cookie jar and use only the header cookie.

readme.txt
=> Tested WP and PHP versions.

lib/class-api.php, lib/class-helpers.php, lib/class-options.php, uninstall.php, wp-to-diaspora.php
Make a few corrections to the code.
=> Scrutinize

lib/class-helpers.php, lib/class-options.php
=> Correct debug check.

js/wp-to-diaspora.js, lib/class-api.php, lib/class-contextual-help.php, lib/class-options.php, readme.txt, wp-to-diaspora.php
Add help for when CA SSL certificates aren't working as they should.
Fixes #54
=> SSL certificates

.travis.yml, bin/install-wp-tests.sh, phpunit.xml, tests/bootstrap.php
Base skeleton for tests using Travis-CI and PHPUnit.
=> Add travis and phpunit to the mix.

.editorconfig, .scrutinizer.yml, css/wp-to-diaspora.css, js/wp-to-diaspora.js, lib/class-api.php, lib/class-contextual-help.php, lib/class-helpers.php, lib/class-options.php, lib/class-post.php, readme.txt, uninstall.php, wp-to-diaspora.php
Make the majority of the code adhere to the WordPress coding standards.
=> Wp coding standards

.editorconfig, .scrutinizer.yml, .travis.yml
Use the .editorconfig also used by WordPress Core.
=> Some mini indentation fixes.

lib/class-post.php, readme.txt
=> Correct the way all tags are added to the post.

js/wp-to-diaspora.js, lib/class-helpers.php, lib/class-options.php, wp-to-diaspora.php
Step closer to cleanly implementing #41
=> Debugging for AJAX call

readme.txt, wp-to-diaspora.php
=> Add minimum WordPress and PHP version checks.

lib/class-post.php, readme.txt, wp-to-diaspora.php
Add Filters for Post Title and 'Originally posted at'. Closes #55 #7 #10
=> Add filters for post title and posted at link / update version 1.5.4

lib/class-post.php
@gutobenn I realised that I had overwritten your `$default` variable name.
This PR adds it again, because it makes a lot more sense and is more understandable.
=> Do some filter variable renaming that make more sense.

.travis.yml, lib/class-api.php, tests/helpers/http-request-filters.php, tests/tests-api.php
API tests have been completely rewritten and optimised.
Big step towards #103
=> New unit tests for WP2D_API

css/wp-to-diaspora.css, js/wp-to-diaspora.js, lib/class-options.php, readme.txt
This change makes the plugin work properly even if Javascript is disabled.
Fixes #116
=> Make plugin no-js friendly

lib/class-helpers.php, tests/tests-helpers.php
Add most test for the WP2D helpers.
=> Tests for helpers

lib/class-api.php, lib/class-helpers.php, lib/class-options.php, lib/class-post.php, tests/bootstrap.php, tests/helpers/http-request-filters.php, tests/helpers/wp2d-api.php, tests/tests-api.php, tests/tests-wp-to-diaspora.php, wp-to-diaspora.php
Add new tests for main class.
Improve error handling for API class.
=> Additional tests and some API updates

README.md, lib/class-api.php, readme.txt, tests/helpers/http-request-filters.php, tests/helpers/wp2d-api.php, tests/tests-api.php, tests/tests-helpers.php, tests/tests-wp-to-diaspora.php, wp-to-diaspora.php
Bump version numbers where necessary.
Update links in documentation to use HTTPS if available.
Slight changes in documentation texts.
=> Prepare for release 1.7

phpunit.xml
Whitelist files that should be used for code coverage.
=> Fix the coverage file generation.

README.md, languages/wp-to-diaspora-de_DE.po, languages/wp-to-diaspora-es_ES.po, languages/wp-to-diaspora-fr_FR.po, languages/wp-to-diaspora-it_IT.po, languages/wp-to-diaspora-ja.po, languages/wp-to-diaspora-pt_BR.po, languages/wp-to-diaspora-ro_RO.po, languages/wp-to-diaspora-ru_RU.po, languages/wp-to-diaspora.pot, lib/class-contextual-help.php, lib/class-post.php, readme.txt, wp-to-diaspora.php
@gutobenn This should be ok, yes?
Would appreciate a check to make sure I didn't forget anything silly.
I left your GitHub profile there as the author link 👍
=> Move repo to DiasPHPora organisation.

lib/class-post.php, readme.txt
This PR adds the feature of passing the WP2D_Post object to the filters to allow total access to all post information.
=> Pass WP2D object to filter to allow complete freedom of customisations.

composer.json, composer.lock, readme.txt
=> Update html-to-markdown to 4.8.1

.travis.yml, readme.txt
Regarding HHVM 4.0 test failing, see here:
https://github.com/composer/composer/issues/7986#issuecomment-463247271
=> Update travis test matrix for latest versions of WP and PHP.

js/wp-to-diaspora.js, lib/class-api.php, lib/class-contextual-help.php, lib/class-helpers.php, lib/class-options.php, phpunit.xml.dist, readme.txt, tests/tests-helpers.php, tests/tests-wp-to-diaspora.php, wp-to-diaspora.php
- Correct error for failed pod connection checks.
- Introduce WP2D_ENC_KEY for password encryption.
- Monitor for AUTH_KEY to notify user to re-save credentials.
Fixes #161
=> Improved credential encryption

lib/class-wp2d-post.php, readme.txt
Hopefully for good this time!
Fixes #160
Fixes #169
=> Fix duplicate posting problem
